import { PRINT, DOC_SIZES, formatDate, avatarFallback } from './print';
import { DocumentData } from './types';

const S = DOC_SIZES.profile;

const Row = ({ label, value }: { label: string; value: string }) => (
  <div
    style={{
      display: 'flex',
      gap: 24,
      padding: '16px 0',
      borderBottom: `1px solid ${PRINT.ruleHairline}`,
    }}
  >
    <div
      style={{
        width: 168,
        flexShrink: 0,
        fontFamily: PRINT.mono,
        fontSize: 12,
        letterSpacing: '0.16em',
        textTransform: 'uppercase',
        color: PRINT.inkSubtle,
        paddingTop: 3,
      }}
    >
      {label}
    </div>
    <div style={{ flex: 1, fontSize: 17, lineHeight: 1.65, color: PRINT.ink }}>{value}</div>
  </div>
);

export default function ProfileSheet({ data }: { data: DocumentData }) {
  return (
    <div
      style={{
        width: S.width,
        height: S.height,
        background: PRINT.paper,
        fontFamily: PRINT.sans,
        padding: '70px 78px',
        boxSizing: 'border-box',
        display: 'flex',
        flexDirection: 'column',
        overflow: 'hidden',
      }}
    >
      <div
        style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'baseline',
          borderBottom: `2px solid ${PRINT.accent}`,
          paddingBottom: 18,
        }}
      >
        <span style={{ fontFamily: PRINT.serif, fontSize: 26, color: PRINT.accent }}>
          CadastRAR
        </span>
        <span
          style={{
            fontFamily: PRINT.mono,
            fontSize: 12,
            letterSpacing: '0.2em',
            textTransform: 'uppercase',
            color: PRINT.inkSubtle,
          }}
        >
          Profile sheet
        </span>
      </div>

      <div style={{ display: 'flex', gap: 34, alignItems: 'center', margin: '46px 0 40px' }}>
        <img
          src={data.image || avatarFallback(data.title)}
          alt=""
          style={{
            width: 156,
            height: 156,
            borderRadius: 4,
            objectFit: 'cover',
            border: `1px solid ${PRINT.rule}`,
            flexShrink: 0,
          }}
        />
        <div style={{ minWidth: 0 }}>
          <div
            style={{
              fontFamily: PRINT.serif,
              fontSize: 54,
              fontWeight: 600,
              lineHeight: 1.03,
              letterSpacing: '-0.02em',
              color: PRINT.ink,
            }}
          >
            {data.title}
          </div>
          <div style={{ marginTop: 12, fontSize: 16, color: PRINT.inkMuted }}>
            {data.tags.slice(0, 6).join(' · ')}
          </div>
        </div>
      </div>

      <Row label="Description" value={data.body} />
      <Row label="Tags" value={data.tags.join(', ')} />
      <Row label="Registered" value={formatDate(data.createdAt)} />
      <Row label="Registrar" value={data.createdBy} />

      <div
        style={{
          marginTop: 'auto',
          fontFamily: PRINT.mono,
          fontSize: 12,
          color: PRINT.inkSubtle,
        }}
      >
        Generated by CadastRAR
      </div>
    </div>
  );
}
